Repository GlueOps/vault-init-controller, pull requests merged in 2025-05, with the labels that each got.

#114 feat: update boto3 -> boto3[crt] and to the latest version
  requirements.txt
Labels: enhancement, minor, include-in-release-notes, Review effort 1/5

#116 refactor for considering
  secret_backend/config.py
Labels: Review effort 3/5

#118 fix restoring algorithm
  secret_backend/config.py
Labels: Review effort 2/5
